name: Deploy

on:
  push:
    branches:
      - dev
    tags:
      - 'release-v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for ARM build on x86 GitHub runner)
        uses: docker/setup-qemu-action@v3

      - name: Make docker image tag
        id: make-image-tag
        env:
          REGISTRY: docker.holyflows.com
          IMAGE_NAME: cfm/church-financial-account-grpc
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            export IMAGE_TAG=dev
          elif [[ $GITHUB_REF == 'refs/tags/release'* ]]; then
            export IMAGE_TAG=${GITHUB_REF#refs/*/}
          fi
          echo ::set-output name=NAME::$REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.make-image-tag.outputs.NAME }}
          build-args: |
            TOKEN_FOR_GITHUB=${{ secrets.TOKEN_FOR_GITHUB }}
